package com.jenkins_demo.dtos;

import com.jenkins_demo.validationgrps.ValidationGroups;
import com.jenkins_demo.validationgrps.ValidationGroups.OnCreate;
import com.jenkins_demo.validationgrps.ValidationGroups.OnUpdate;

import jakarta.validation.Valid;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;

public class UserDto {

	@Null(groups = ValidationGroups.OnCreate.class, message = "Id is autogenerated, don't pass it")
	@NotNull(groups = ValidationGroups.OnUpdate.class, message = "Id is required for updates")
	private Long id;
	
	@NotBlank(groups = {ValidationGroups.OnCreate.class, ValidationGroups.OnUpdate.class}, message = "Username cannot be blank")
	private String userName;
	
	@Min(value = 1)
	@Min(value = 1, groups = {ValidationGroups.OnCreate.class, ValidationGroups.OnUpdate.class}, message = "Age must be greater than 0")
	private int age;
	
	
	@Email(groups = {ValidationGroups.OnCreate.class,ValidationGroups.OnUpdate.class}, message = "Invalid email format")
	private String emailAddress;

	@NotNull(
		    groups = {ValidationGroups.OnCreate.class, ValidationGroups.OnUpdate.class}, 
		    message = "Address payload is required"
		)
		@Valid // 💡 @Valid stays here to propagate the selected group down into AddressDto fields!
		private AddressDto address;
	
	
	
	public UserDto(
			@Null(groups = OnCreate.class, message = "Id is autogenerated, don't pass it") @NotNull(groups = OnUpdate.class, message = "Id is required for updates") Long id,
			@NotBlank(groups = { OnCreate.class,
					OnUpdate.class }, message = "Username cannot be blank") String userName,
			@Min(1) @Min(value = 1, groups = { OnCreate.class,
					OnUpdate.class }, message = "Age must be greater than 0") int age,
			@Email(groups = { OnCreate.class, OnUpdate.class }, message = "Invalid email format") String emailAddress,
			@NotNull(message = "Address payload is required") @Valid AddressDto address) {
		super();
		this.id = id;
		this.userName = userName;
		this.age = age;
		this.emailAddress = emailAddress;
		this.address = address;
	}



	public Long getId() {
		return id;
	}



	public void setId(Long id) {
		this.id = id;
	}



	public String getUserName() {
		return userName;
	}



	public void setUserName(String userName) {
		this.userName = userName;
	}



	public int getAge() {
		return age;
	}



	public void setAge(int age) {
		this.age = age;
	}



	public String getEmailAddress() {
		return emailAddress;
	}



	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}



	public AddressDto getAddress() {
		return address;
	}



	public void setAddress(AddressDto address) {
		this.address = address;
	}



	public UserDto() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	
	
}
