pipeline {

    agent any

    stages {

        stage('Build') {
            steps {
                dir('JenkinsDemo') {
                    sh 'chmod +x mvnw'
                    sh './mvnw clean package'
                }
            }
        }

        stage('Deploy') {
            steps {

                sshagent(['aws-prod-ssh']) {

                    sh '''
                    scp -o StrictHostKeyChecking=no \
                    JenkinsDemo/target/*.jar \
                    ubuntu@15.135.89.196:/opt/spring-app/app.jar

                    ssh -o StrictHostKeyChecking=no \
                    ubuntu@15.135.89.196 \
                    "sudo systemctl restart spring-app"
                    '''
                }
            }
        }
    }
}
