pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                url: 'https://github.com/your/repo.git'
            }
        }

        stage('Build') {
            steps {
                sh './mvnw clean package'
            }
        }

        stage('Deploy') {

            steps {

                sshagent(['aws-prod-ssh']) {

                    sh '''
                    scp target/*.jar ubuntu@AWS_IP:/opt/spring-app/app.jar

                    ssh ubuntu@AWS_IP '
                    sudo systemctl restart spring-app
                    '
                    '''
                }
            }
        }
    }
}
