package com.jenkins_demo.controllers;

import com.jenkins_demo.dtos.UserDto;
import com.jenkins_demo.validationgrps.ValidationGroups;

import jakarta.validation.Valid;
import jakarta.validation.constraints.Min;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.atomic.AtomicLong;

@RestController
//@RequestMapping("/api/users")
public class UserController {

    // Simulating an in-memory database
    private final Map<Long, UserDto> userDatabase = new HashMap<>();
    private final AtomicLong idGenerator = new AtomicLong(1); // Simulates database autoincrement

    // 1. CREATE FLOW
    @PostMapping("/create")
    public ResponseEntity<String> createUser(
    		@Validated(ValidationGroups.OnCreate.class) @RequestBody UserDto userDto
    ) {
        // Generate an ID automatically (Simulating DB behavior)
        Long newId = idGenerator.getAndIncrement();
        userDto.setId(newId);
        
        // Save to our in-memory map
        userDatabase.put(newId, userDto);
        
        return ResponseEntity.ok("User created with autogenerated ID: " + newId);
    }

    // 2. UPDATE FLOW
    @PutMapping("/update/{id}") // Fixed syntax to use {id}
    public ResponseEntity<String> updateUser(
        @PathVariable("id") @Min(value = 1, message = "URL ID must be greater than 0") Long id, // 2. Validated path variable
        @Validated(com.jenkins_demo.validationgrps.ValidationGroups.OnUpdate.class) @RequestBody UserDto userDto
    ) {
        // Core sanity check: Ensure URL id matches the payload id
        if (!id.equals(userDto.getId())) {
            return ResponseEntity.badRequest().body("Path ID and Request Body ID must match.");
        }

        if (!userDatabase.containsKey(userDto.getId())) {
            return ResponseEntity.badRequest().body("User with ID " + userDto.getId() + " does not exist.");
        }

        userDatabase.put(userDto.getId(), userDto);
        return ResponseEntity.ok("User details updated successfully in-memory for ID: " + userDto.getId());
    }
}